branches:
  except:
  - "/^wip/"
language: node_js
node_js:
- '8'
before_install:
- yarn global add greenkeeper-lockfile@1
before_script:
- greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
- yarn lint
- TZ="America/Los_Angeles" yarn test
after_success: yarn run coverage
notifications:
  slack:
    secure: D1Bp4lEnrf45UHEo4vnkMVagOg2LbZ8cm0HPEn2wbLKvZvraeU5Wnr/C9Le1w2arQwjCSkIQrIVmG9bZCdUDfkmNy+9wyAvzYzLvTv3aSRf764BuZCCdLi82V6R/NGwWp/36aWufk5EtbEO9TgayhzmDutKIB4NfqhU8Zjn+hClSwxk6dTzI3K9vuuKEXn1hM3q9c+S+9hROxf2f1/dXXjcYSov5FklmN82SFTLKRAt1dAvZRV0cqXkln2ZW8q4Vr8lyt0sHf6ocZsmxn0pkLGmxjzr9/ufsgHbPGAyYfqPs3mk25heAbJapQWq1nTPoJ7tlhbtzZ7TZ3yHj/FqwWXFJdyRUL1Y0OeA/L7AIHPXcV+V5iYHasvt1qqj72shRVrqokAofZ0q4m+6cISqvE0GXl5gFHznmTJ5AOYH4TSE1OcUyxnlz/yuwx4OC8xHERLGJQmLUDNh+2GY6BZ37Vfw215Pui3blEbKMf/F5cU+0/esaErsGDSkxMCO/zxXguGrzjSNjvFWM7Pt3iYZKNDcz9tpePd/bEhSdIWOyduM9lg2f6QAgYigksGxn56MVvlWUw9pjbvPgW/aryCo5G4ZDZGy/wN84rc0d664S/uiiJErfUr1FbY15LyA4utlKSmym1FIZory2kQc4IW/3ioOzOljBO64r66T5AmrkKpg=
deploy:
  provider: npm
  email: gcampagn@cs.stanford.edu
  api_key:
    secure: mxYGxLfKbzuN+6YX8oNh0mTU25WZv8VVXAwObDY1N0Sq8Iujt27SsHeEyqa+HpyWRReHqAnU3llWeojpEO+JTvA3N4fyL7UplvKs18SpACNTC0R+8F6MkhyW56nSptU67oblgvKWXHgqHqqrtxWShtfDK1FerxeZmG3aXyzLVqS6rt/G32Zc5WA2dY1n4lxMhAN2zHMItgY/mwfbM7XyPeitFOe7BnEGlACrGXhUlc4TKulZjjcwr1ltP4V83n1N8DKssvsxehumWVkrrNbJnf9GO3Kp4Bbq3PBzd9ynyAxbCtEU05Hp7p59qn5vHPPB1SPmxmUJHNoU15xrhUd8gU5/Gp60ZQw7CpD91jt5V9pqK7+YTYLcAQDvPRsdJSAsCVL1w3gxicMxCgeLwT9ynHJ5TKKLlwkUroCj73XVa/Aoto7b1KwtzddIrDbRXlVe611Vrr4SGxA9vDyznq9lBLPC6LCgcTKG700VQk82tlHT7VGdJTbjgfYUNXXvfEDpNnEaIrt40CoYVQh4iCfdOJ9lOd6RU+B/xT8Wjf+dlcD3gqjcSstyaSjNrAOIxRRixiUNe3dv28sixW1Tw14umLP2C/fUUMK/fMN2HLHPaXNGVYVYH3FD17lu0g6/rBd4ssFkxgDe/1N8MuQ564ZbwWf7H01DEuzUFYlvf4+nbo8=
  on:
    tags: true
    repo: stanford-oval/almond-dialog-agent
env:
  global:
    secure: Vh7UgT8h+Rw/zBGxuCqfZinoDg98aoCfDKYFZSsyAy2zQo4s2fg9VNoYpQH6RjHKWHUYZeKd19bftM84ynZkzZOmp81qtmuKYEMNkVskuRGLg8b9LlGPEtzbvZW04RKfVwLbt2wh51XEOe8mKV1VNgyEBWrwY/CijxLPk8jVfWAi0TKFkOMf4c8lD2PtMJ8+L98AW67cUfV6Hzr+jYHA97GRPbXE0N6Aq66FcQsmJuf/Bbmvr7It55RzgeJ6+VDN8hFB+g8JEq9ofwVaWzS0D4tVliHN9TM3kb9C/mPVOk2LgY7BCnZ3uF3nBnulTHtJ1qcQZq58hsYa0kVcCJ3m6cvqtKEHgKdutSAg5ttsBoqXE/HFJx0wuIn6LgmqCGR8ZBmeIjVBIvy4R/RYwr4K5b2g+8LaGwVH7K3QJGxHaBIGV7Ge8N7xKBruOTVzQxm1T3qD7yTvIgXzQVAfXgSHHeFyFBWhIACPI5/pkVV+lTWSl44C6Yb7fCMAEtAw6Awv2wbodC4TYgogylSfWUWAyhaZEnmify2ew7+ZcoiWMcVKg99bBylyelXTW/9HnI2TSjIkHUvwUDMHVafjA4QJIZuPOu/7uwTomqcB7HMSaW1eiFxHYHOVrE4iAswrkoWgFkmaWoMY8Ft40jjnIYf/vBmR8mjkuAuZd4oSLVmE6fU=
