branches:
  except:
  - "/^wip/"
language: node_js
node_js:
- '8'
before_install:
- yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
- yarn lint
- yarn test
after_success: yarn run coverage
notifications:
  slack:
    secure: Xmek8u60Ni2iq7E0qzC5RFa3LufmqESJAsBu6IIAOcGjrkVKrqUyUXbUjnbdATrAN78puupQukhdGLLTj/EaSqSSliQrslQ9F9DgusRL/jZ3tkjjWdtfuTNpfXEJzkKM1rM9UI5PSbSsGnNO1qcYs8VKnTvzoKKkW3Z8h625ZpRzpTnE1UEFlkcOFEIB08Ahlo756/Ptinb55TI6hbmE/hwY1lHuPYHHWUBlSpuUQhSL1PkIzocTFkiKohHMKOszo/ZQTWBN+4Te9mXzR8p2J9Inwb9fBdiLo7Xaf896kUoAIUVvH0WpniooXAvMTxjrLL9OYBRfpFHM/7U1jlTigIiGXXCJOXQBshhs9wxhyDnEfinHSjIfCjDugzGspnPW2MTZeYgyBssznTkjCV4/14dQuRE1I/8sfA0Isqd0R2yBu3NstyiDlmZYEtRXzorhZ3wsDh2v3Q3dS/b6yrT99itnhzhMPALPjgcxyxUQMoFLZrNYOZKIhKporxoxHiP87SgQeto1UxOXrNErseQTc+tHI3mjAabWvFMGEgxCuc5aA9BesbgWBTX3Z1OEHBFIA0pYpINAYl0Dm7+pYamPjoks8jIWSIYEyq/ut3td9MBzVmU9+HncMi0Kqmw1+tmk90hfwkFhxOnynxf1k+T1gvSWy3t/NBXU6JSZetbeoIU=
deploy:
  provider: npm
  email: gcampagn@cs.stanford.edu
  api_key:
    secure: mxYGxLfKbzuN+6YX8oNh0mTU25WZv8VVXAwObDY1N0Sq8Iujt27SsHeEyqa+HpyWRReHqAnU3llWeojpEO+JTvA3N4fyL7UplvKs18SpACNTC0R+8F6MkhyW56nSptU67oblgvKWXHgqHqqrtxWShtfDK1FerxeZmG3aXyzLVqS6rt/G32Zc5WA2dY1n4lxMhAN2zHMItgY/mwfbM7XyPeitFOe7BnEGlACrGXhUlc4TKulZjjcwr1ltP4V83n1N8DKssvsxehumWVkrrNbJnf9GO3Kp4Bbq3PBzd9ynyAxbCtEU05Hp7p59qn5vHPPB1SPmxmUJHNoU15xrhUd8gU5/Gp60ZQw7CpD91jt5V9pqK7+YTYLcAQDvPRsdJSAsCVL1w3gxicMxCgeLwT9ynHJ5TKKLlwkUroCj73XVa/Aoto7b1KwtzddIrDbRXlVe611Vrr4SGxA9vDyznq9lBLPC6LCgcTKG700VQk82tlHT7VGdJTbjgfYUNXXvfEDpNnEaIrt40CoYVQh4iCfdOJ9lOd6RU+B/xT8Wjf+dlcD3gqjcSstyaSjNrAOIxRRixiUNe3dv28sixW1Tw14umLP2C/fUUMK/fMN2HLHPaXNGVYVYH3FD17lu0g6/rBd4ssFkxgDe/1N8MuQ564ZbwWf7H01DEuzUFYlvf4+nbo8=
  on:
    tags: true
    repo: Stanford-Mobisocial-IoT-Lab/almond-dialog-agent
env:
  global:
    secure: Vh7UgT8h+Rw/zBGxuCqfZinoDg98aoCfDKYFZSsyAy2zQo4s2fg9VNoYpQH6RjHKWHUYZeKd19bftM84ynZkzZOmp81qtmuKYEMNkVskuRGLg8b9LlGPEtzbvZW04RKfVwLbt2wh51XEOe8mKV1VNgyEBWrwY/CijxLPk8jVfWAi0TKFkOMf4c8lD2PtMJ8+L98AW67cUfV6Hzr+jYHA97GRPbXE0N6Aq66FcQsmJuf/Bbmvr7It55RzgeJ6+VDN8hFB+g8JEq9ofwVaWzS0D4tVliHN9TM3kb9C/mPVOk2LgY7BCnZ3uF3nBnulTHtJ1qcQZq58hsYa0kVcCJ3m6cvqtKEHgKdutSAg5ttsBoqXE/HFJx0wuIn6LgmqCGR8ZBmeIjVBIvy4R/RYwr4K5b2g+8LaGwVH7K3QJGxHaBIGV7Ge8N7xKBruOTVzQxm1T3qD7yTvIgXzQVAfXgSHHeFyFBWhIACPI5/pkVV+lTWSl44C6Yb7fCMAEtAw6Awv2wbodC4TYgogylSfWUWAyhaZEnmify2ew7+ZcoiWMcVKg99bBylyelXTW/9HnI2TSjIkHUvwUDMHVafjA4QJIZuPOu/7uwTomqcB7HMSaW1eiFxHYHOVrE4iAswrkoWgFkmaWoMY8Ft40jjnIYf/vBmR8mjkuAuZd4oSLVmE6fU=
